# Generated by Django 6.0 on 2026-01-03 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telegram username must start with '@'", regex="^@"
                    )
                ],
            ),
        ),
    ]
