# Generated by Django 6.0 on 2025-12-14 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempost',
            name='university',
            field=models.CharField(choices=[('AASTU', 'Addis Ababa Science and Technology Univesity')], default='AASTU', max_length=10),
        ),
    ]
