# Generated by Django 6.0 on 2026-01-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_contactrequest_created_at_itempost_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="itempost",
            name="university",
            field=models.CharField(
                choices=[
                    ("AASTU", "Addis Ababa Science and Technology Univesity"),
                    ("ASTU", "Adama Science and Technology University"),
                    ("AAU", "Addis Ababa University"),
                ],
                default="AASTU",
                max_length=10,
            ),
        ),
    ]
