# Generated by Django 6.0 on 2026-01-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_contactrequest_is_accepted_alter_itempost_university"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=10, unique=True)),
                ("full_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Universities",
            },
        ),
        migrations.AddField(
            model_name="itempost",
            name="university_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="items.university",
            ),
        ),
    ]
