# Generated by Django 6.0 on 2026-01-03 19:51

from django.db import migrations


def populate_universities(apps, schema_editor):
    University = apps.get_model("items", "University")
    ItemPost = apps.get_model("items", "ItemPost")

    universities = {
        "AASTU": "Addis Ababa Science and Technology University",
        "ASTU": "Adama Science and Technology University",
        "AAU": "Addis Ababa University",
    }

    university_objs = {}
    for short, full in universities.items():
        obj, _ = University.objects.get_or_create(short_name=short, full_name=full)
        university_objs[short] = obj

    for item in ItemPost.objects.all():
        if item.university in university_objs:
            item.university_fk = university_objs[item.university]
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_university_itempost_university_fk"),
    ]

    operations = [
        migrations.RunPython(populate_universities),
    ]
