# Generated by Django 6.0 on 2026-01-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_auto_20260103_1951"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itempost",
            name="university",
        ),
        migrations.RenameField(
            model_name="itempost",
            old_name="university_fk",
            new_name="university",
        ),
    ]
