# Generated by Django 6.0 on 2026-01-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_remove_itempost_university_fk_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="itempost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="itempost",
            name="university",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="items.university",
            ),
            preserve_default=False,
        ),
    ]
